

# BINARIES

cc_binary(
    name = "radix_sort_main",
    srcs = ["radix_sort_main.cc"],
    deps = [
        "//sort/radix_sort:radix_sort",
        "//third_party/gflags",
        "//third_party/glog",
    ],
    linkopts = ["-lm"],
)
